flghtnum = input('Номер рейса: ')
arlnru = input('Название авиакомпании (на русском языке): ')
arlnen = input('Название авиакомпании (на английском языке): ')
dstntnru = input('Город прилёта (на русском языке): ')
dstntnen = input('Город прилёта (на английском языке): ')
print('Заканчивается посадка на рейс', flghtnum, arlnru, 'до', dstntnru)
print('This is the final boarding call for', arlnen, 'flight', flghtnum, 'to', dstntnen)
